version: '3.8'
services:

  med-api:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=med-api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: on-failure
    volumes:
      - med-api-data:/var/lib/postgresql/data

  med-api-test:
    image: postgres
    environment:
      - POSTGRES_DB=med-api-test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"

volumes:
  med-api-data: